# Generated by Django 3.1.2 on 2020-10-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='surveyID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.TextField(max_length=100),
        ),
    ]
