# Generated by Django 3.1.2 on 2020-10-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(null=True, related_name='surveys_question', to='survey.Question'),
        ),
    ]
