# Generated by Django 3.1.2 on 2020-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20201007_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(related_name='surveys_question', to='survey.Question'),
        ),
    ]
