# Generated by Django 3.1.2 on 2020-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20201007_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_body',
            field=models.CharField(default='Type Question Here', max_length=250),
            preserve_default=False,
        ),
    ]
