# Generated by Django 3.1.2 on 2020-10-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='results',
            field=models.ManyToManyField(blank=True, related_name='survey_result', to='survey.Result'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_link',
            field=models.URLField(blank=True),
        ),
    ]
